name: 'auto-cancel-action'
description: 'Cancel redundant actions'
inputs:
  access_token:
    description: 'Github token'
    required: true
  debug:
    description: 'Be verbose'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
